package startdesign;
import static javax.swing.text.html.HTML.Tag.FONT;

import java.io.FileOutputStream;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.text.Document;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JCheckBox;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author urmikapoor
 */
public class AdminTT extends javax.swing.JFrame {

	/**
	 * Creates new form Constraints
	 */
	public AdminTT() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTabbedPane1.setToolTipText("Admin");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
				);
		jPanel1 = new javax.swing.JPanel();

		lblNewLabel = new JLabel("No of Subjects:");

		lblNewLabel_1 = new JLabel("Teachers per Classroom:");

		lblNewLabel_2 = new JLabel("No of slots:");

		lblNewLabel_3 = new JLabel("");

		JTextArea textArea = new JTextArea();

		JTextArea textArea_1 = new JTextArea();

		JTextArea textArea_2 = new JTextArea();

		JButton btnSubmit = new JButton("Submit");
		btnSubmit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
			}
		});

		JLabel lblNewLabel_4 = new JLabel("Years:");

		textField = new JTextField();
		textField.setColumns(10);

		JLabel lblNewLabel_5 = new JLabel("No of grades:");

		textField_1 = new JTextField();
		textField_1.setColumns(10);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addContainerGap()
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(lblNewLabel)
														.addGap(58)
														.addComponent(textArea, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE))
														.addComponent(lblNewLabel_3)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																		.addComponent(lblNewLabel_1)
																		.addComponent(lblNewLabel_2))
																		.addPreferredGap(ComponentPlacement.UNRELATED)
																		.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																				.addComponent(textArea_1, GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
																				.addComponent(textArea_2, GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
																				.addGap(34)
																				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																						.addGroup(jPanel1Layout.createSequentialGroup()
																								.addComponent(lblNewLabel_4)
																								.addGap(36)
																								.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
																								.addGroup(jPanel1Layout.createSequentialGroup()
																										.addPreferredGap(ComponentPlacement.RELATED)
																										.addComponent(lblNewLabel_5)
																										.addPreferredGap(ComponentPlacement.RELATED)
																										.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
																										.addGroup(jPanel1Layout.createSequentialGroup()
																												.addGap(77)
																												.addComponent(btnSubmit)))
																												.addContainerGap(318, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(53)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblNewLabel)
								.addComponent(textArea, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblNewLabel_4)
								.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGap(18)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(lblNewLabel_1)
										.addComponent(textArea_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(lblNewLabel_5)
										.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(lblNewLabel_2)
												.addComponent(textArea_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
												.addGap(18)
												.addComponent(lblNewLabel_3)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(btnSubmit)
												.addContainerGap(264, Short.MAX_VALUE))
				);
		jPanel1.setLayout(jPanel1Layout);

		jTabbedPane1.addTab("Constraints", jPanel1);
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		name = new javax.swing.JTextField();
		s1 = new javax.swing.JTextField();
		s2 = new javax.swing.JTextField();
		s3 = new javax.swing.JTextField();
		s4 = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String name1=name.getText();
				String sub1=s1.getText();
				String sub4=s4.getText();
				String sub3=s3.getText();
				String sub2=s2.getText();

				if(sub1.length()==0||sub2.length()==0||sub3.length()==0||sub4.length()==0||sub1==null||sub2==null||sub3==null||sub4==null)
				{
					JOptionPane.showMessageDialog(null, "All the details are not filled!!!Please fill all the details." );
				}
				else
					JOptionPane.showMessageDialog(null, "All the details are filled!!!Please fill all the details." );



			}
		});
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();

		jLabel2.setText("Name:");

		jLabel3.setText("Subject1:");

		jLabel4.setText("Subject2:");

		jLabel5.setText("Subject3:");

		jLabel6.setText("Subject4:");

		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 14), new java.awt.Color(0, 51, 255))); // NOI18N

		jButton1.setText("Add Details");

		jButton2.setText("Edit Details");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Create TT");

		jButton4.setText("Print TT");
		

		jButton5.setText("Mail TT");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addGap(24, 24, 24)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jButton1)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton3)
										.addComponent(jButton2)
										.addComponent(jButton4)
										.addComponent(jButton5)))
										.addContainerGap(31, Short.MAX_VALUE))
				);
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addGap(35, 35, 35)
						.addComponent(jButton1)
						.addGap(18, 18, 18)
						.addComponent(jButton2)
						.addGap(18, 18, 18)
						.addComponent(jButton3)
						.addGap(18, 18, 18)
						.addComponent(jButton4)
						.addGap(18, 18, 18)
						.addComponent(jButton5)
						.addContainerGap(48, Short.MAX_VALUE))
				);

		JCheckBox chckbxActive = new JCheckBox("Active");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(24)
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(jLabel3)
												.addComponent(jLabel4)
												.addComponent(jLabel5)
												.addComponent(jLabel6))
												.addGap(29)
												.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
														.addComponent(s4)
														.addComponent(s1)
														.addComponent(s2)
														.addComponent(s3)
														.addComponent(name, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)))
														.addComponent(chckbxActive))
														.addPreferredGap(ComponentPlacement.RELATED)
														.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addContainerGap(434, Short.MAX_VALUE))
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGap(97)
										.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(name, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
												.addGap(18)
												.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(s1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
														.addGap(18)
														.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
																.addComponent(jLabel4)
																.addComponent(s2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
																.addGap(18)
																.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
																		.addComponent(jLabel5)
																		.addComponent(s3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
																		.addGap(18)
																		.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
																				.addComponent(jLabel6)
																				.addComponent(s4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
																				.addGap(18)
																				.addComponent(chckbxActive))
																				.addGroup(jPanel2Layout.createSequentialGroup()
																						.addGap(35)
																						.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
																						.addContainerGap(134, Short.MAX_VALUE))
				);
		jPanel2.setLayout(jPanel2Layout);

		jTabbedPane1.addTab("Teacher Details", jPanel2);
		jPanel3 = new javax.swing.JPanel();

		JLabel lblYear = new JLabel("Year :");

		JLabel lblDivision = new JLabel("Division:");

		textField_2 = new JTextField();
		textField_2.setColumns(10);

		textField_3 = new JTextField();
		textField_3.setColumns(10);

		final JCheckBox c1 = new JCheckBox("New check box");

		JCheckBox chckbxNewCheckBox_1 = new JCheckBox("New check box");

		JCheckBox chckbxNewCheckBox_2 = new JCheckBox("New check box");

		JCheckBox checkBox = new JCheckBox("New check box");

		JCheckBox checkBox_1 = new JCheckBox("New check box");

		JCheckBox checkBox_2 = new JCheckBox("New check box");

		JCheckBox checkBox_3 = new JCheckBox("New check box");

		JCheckBox checkBox_4 = new JCheckBox("New check box");

		JCheckBox checkBox_5 = new JCheckBox("New check box");

		JCheckBox checkBox_6 = new JCheckBox("New check box");

		JCheckBox checkBox_7 = new JCheckBox("New check box");

		JCheckBox checkBox_8 = new JCheckBox("New check box");

		JCheckBox checkBox_9 = new JCheckBox("New check box");

		JCheckBox checkBox_10 = new JCheckBox("New check box");

		JCheckBox checkBox_11 = new JCheckBox("New check box");

		JCheckBox checkBox_12 = new JCheckBox("New check box");

		JCheckBox checkBox_13 = new JCheckBox("New check box");

		JCheckBox checkBox_14 = new JCheckBox("New check box");

		JCheckBox checkBox_15 = new JCheckBox("New check box");

		JCheckBox checkBox_16 = new JCheckBox("New check box");

		JCheckBox checkBox_17 = new JCheckBox("New check box");

		JCheckBox checkBox_18 = new JCheckBox("New check box");

		JCheckBox checkBox_19 = new JCheckBox("New check box");

		JCheckBox checkBox_20 = new JCheckBox("New check box");

		JCheckBox checkBox_21 = new JCheckBox("New check box");
 final JLabel  lblNewLabel_6 = new JLabel("");
		
		final JLabel l1 = new JLabel("");

		JButton btnCreate = new JButton("Create");
		btnCreate.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				l1.setText("English");			}
		});
		
		
		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addGap(24)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addComponent(lblYear)
							.addGap(18)
							.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addComponent(lblDivision)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(textField_3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addComponent(btnCreate))
					.addGap(66)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(checkBox_21)
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addComponent(checkBox_18)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(checkBox_19)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(checkBox_20))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING, false)
								.addGroup(Alignment.LEADING, jPanel3Layout.createSequentialGroup()
									.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(checkBox_9, 0, 0, Short.MAX_VALUE)
										.addComponent(checkBox_6, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
										.addComponent(checkBox_3, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
										.addComponent(checkBox, 0, 0, Short.MAX_VALUE)
										.addComponent(c1, GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE))
									.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
										.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
											.addGap(80)
											.addComponent(checkBox_10, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
											.addGroup(jPanel3Layout.createSequentialGroup()
												.addGap(84)
												.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
													.addComponent(lblNewLabel_6)
													.addComponent(l1)
													.addComponent(checkBox_1, GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)
													.addComponent(chckbxNewCheckBox_1, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
													.addComponent(checkBox_4, 0, 0, Short.MAX_VALUE)))
											.addGroup(jPanel3Layout.createSequentialGroup()
												.addGap(80)
												.addComponent(checkBox_7, 0, 0, Short.MAX_VALUE)))))
								.addGroup(Alignment.LEADING, jPanel3Layout.createSequentialGroup()
									.addComponent(checkBox_12, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
									.addComponent(checkBox_13, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
								.addGroup(Alignment.LEADING, jPanel3Layout.createSequentialGroup()
									.addComponent(checkBox_15)
									.addPreferredGap(ComponentPlacement.UNRELATED)
									.addComponent(checkBox_16)
									.addPreferredGap(ComponentPlacement.RELATED, -92, Short.MAX_VALUE)))
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
									.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
										.addGroup(jPanel3Layout.createSequentialGroup()
											.addGap(78)
											.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(checkBox_2, GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
												.addComponent(chckbxNewCheckBox_2, GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
												.addComponent(checkBox_5, 0, 0, Short.MAX_VALUE)))
										.addGroup(jPanel3Layout.createSequentialGroup()
											.addGap(74)
											.addComponent(checkBox_8, 0, 0, Short.MAX_VALUE)))
									.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
										.addGap(74)
										.addComponent(checkBox_11, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel3Layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.UNRELATED)
									.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(checkBox_14, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(checkBox_17))))))
					.addGap(243))
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addGap(40)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblYear)
						.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(c1)
						.addComponent(lblNewLabel_6)
						.addComponent(l1)
						.addComponent(chckbxNewCheckBox_2)
						.addComponent(chckbxNewCheckBox_1))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblDivision)
						.addComponent(textField_3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(checkBox)
						.addComponent(checkBox_2)
						.addComponent(checkBox_1))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(checkBox_3)
						.addComponent(checkBox_4)
						.addComponent(checkBox_5)
						.addComponent(btnCreate))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(checkBox_6)
						.addComponent(checkBox_7)
						.addComponent(checkBox_8))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(checkBox_9)
						.addComponent(checkBox_10)
						.addComponent(checkBox_11))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(checkBox_12)
						.addComponent(checkBox_14)
						.addComponent(checkBox_13))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(checkBox_15)
						.addComponent(checkBox_16)
						.addComponent(checkBox_17))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(checkBox_18)
						.addComponent(checkBox_19)
						.addComponent(checkBox_20))
					.addGap(18)
					.addComponent(checkBox_21)
					.addContainerGap(75, Short.MAX_VALUE))
		);
		jPanel3.setLayout(jPanel3Layout);

		jTabbedPane1.addTab("Create Timetable", jPanel3);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jButton2ActionPerformed

	/*private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		try{
			Document document=new Document();
			PdfWriter.getInstance(document,new FileOutputStream("Report.pdf"));
			document.open();
			document.add(new Paragraph("Easy Timetabler",FontFactory.getFont(FontFactory.Times_BOLD,18,FONT.BOLD,BaseColor.RED)));
			document.close();
			JOptionPane.showMessageDialog("Report created");
		}
		catch(Exception e)
		{
			JOptionPane.showMessageDialog(null,e);

		}
		// TODO add your handling code here:
	}//GEN-LAST:event_jButton4ActionPerformed
*/
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AdminTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AdminTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AdminTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AdminTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminTT().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField name;
	private javax.swing.JTextField s1;
	private javax.swing.JTextField s2;
	private javax.swing.JTextField s3;
	private javax.swing.JTextField s4;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
	private JLabel lblNewLabel_2;
	private JLabel lblNewLabel_3;
	private JTextField textField;
	private JTextField textField_1;
	private JTextField textField_2;
	private JTextField textField_3;
}
